# Generated by Django 5.2.7 on 2025-11-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_pause',
            field=models.BooleanField(default=True),
        ),
    ]
