# Generated by Django 5.2.7 on 2025-11-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_is_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_pause',
            field=models.BooleanField(default=False),
        ),
    ]
