# Generated by Django 5.2.7 on 2025-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('user_profile', '0004_remove_buyerprofile_preferred_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        migrations.AddField(
            model_name='conversation',
            name='buyer',
            field=models.ManyToManyField(related_name='conversations', to='user_profile.buyerprofile'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller',
            field=models.ManyToManyField(related_name='conversations', to='user_profile.sellerprofile'),
        ),
    ]
