# Generated by Django 5.2.7 on 2025-11-01 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_conversation_participants_conversation_buyer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='buyer',
            field=models.ManyToManyField(related_name='buyer_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='seller',
            field=models.ManyToManyField(related_name='seller_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
