# Generated by Django 5.2.7 on 2025-11-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_orderstatushistroy_orderstatushistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
