# Generated by Django 5.2.7 on 2025-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
