# Generated by Django 5.2.7 on 2025-11-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_delete_transaction'),
        ('wallet', '0004_alter_wallettransaction_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='to_user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='amount_cents',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.order'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release'), ('REFUND', 'Refund')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['idempotency_key'], name='wallet_wall_idempot_442271_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['created_at'], name='wallet_wall_created_929d33_idx'),
        ),
    ]
