# Generated by Django 5.2.7 on 2025-10-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('image', models.ImageField(default='avatars/seller.jpeg', upload_to='avatars/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('rating', models.FloatField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
