# Generated by Django 5.2.7 on 2025-10-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_buyerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='preferred_category',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='wishlist_count',
        ),
    ]
